[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.5"

[[constraint]]
  name = "github.com/spf13/viper"
  revision = "aafc9e6bc7b7bb53ddaa75a5ef49a17d6e654be5"

[[override]]
  name = "github.com/spf13/pflag"
  version = "1.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/iancoleman/strcase"

[[constraint]]
  name = "github.com/docker/libcompose"
  revision = "213509acef0fe8f2358f4c0bb977eb3f4889ea15"

[[override]]
  name = "github.com/docker/docker"
  source = "https://github.com/docker/engine.git"
  revision = "200b524eff60a9c95a22bc2518042ac2ff617d07" # 18.09 branch

[[override]]
  name = "github.com/docker/distribution"
  revision = "6664ec703991875e14419ff4960921cce7678bab"

[[override]]
  name = "github.com/docker/cli"
  revision = "v18.09.6"

[[override]]
  name = "github.com/docker/go-metrics"
  revision = "b8fbfd8f51b86cbfefb5f00fd998df220a234337"

[[override]]
  name = "github.com/xeipuuv/gojsonschema"
  revision = "0c8571ac0ce161a5feb57375a9cdf148c98c0f70"

[[constraint]]
  branch = "master"
  name = "github.com/shurcooL/go"

[[constraint]]
  name = "github.com/gorilla/websocket"
  version = "1.4.0"
